package com.stuypulse.robot.subsystems.swerve;

import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.mechanisms.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.mechanisms.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.mechanisms.swerve.SwerveModuleConstantsFactory;
import com.ctre.phoenix6.mechanisms.swerve.SwerveModule.ClosedLoopOutputType;
import com.ctre.phoenix6.mechanisms.swerve.SwerveModuleConstants.SteerFeedbackType;
import com.stuypulse.robot.constants.Ports;
import com.stuypulse.robot.constants.Settings;

import edu.wpi.first.math.util.Units;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class TunerConstants {
    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    private static final Slot0Configs steerGains = new Slot0Configs()
        // .withKP(100).withKI(0).withKD(0.2)
        .withKP(10).withKI(0).withKD(0)
        .withKS(0).withKV(1.5).withKA(0);
    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    private static final Slot0Configs driveGains = new Slot0Configs()
        .withKP(3).withKI(0).withKD(0)
        .withKS(0).withKV(0).withKA(0);

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType steerClosedLoopOutput = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType driveClosedLoopOutput = ClosedLoopOutputType.Voltage;

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final double kSlipCurrentA = 150.0;

    // Initial configs for the drive and steer motors and the CANcoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                // Swerve azimuth does not require much torque output, so we can set a relatively low
                // stator current limit to help avoid brownouts without impacting performance.
                .withStatorCurrentLimit(60)
                .withStatorCurrentLimitEnable(true)
        );
    private static final CANcoderConfiguration cancoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Pigeon2Configuration pigeonConfigs = null;

    // Theoretical free speed (m/s) at 12v applied output;
    // This needs to be tuned to your individual robot
    public static final double kSpeedAt12VoltsMps = 5.21;

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot
    private static final double kCoupleRatio = 3.5714285714285716;

    private static final double kDriveGearRatio = 6.122448979591837;
    private static final double kSteerGearRatio = 21.428571428571427;
    private static final double kWheelRadiusInches = 2;

    private static final boolean kInvertLeftSide = false;
    private static final boolean kInvertRightSide = true;

    private static final String kCANbusName = "Default Name";
    private static final int kPigeonId = 0;


    // These are only used for simulation
    private static final double kSteerInertia = 0.00001;
    private static final double kDriveInertia = 0.001;
    // Simulated voltage necessary to overcome friction
    private static final double kSteerFrictionVoltage = 0.25;
    private static final double kDriveFrictionVoltage = 0.25;

    public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
            .withCANbusName(kCANbusName)
            .withPigeon2Id(kPigeonId)
            .withPigeon2Configs(pigeonConfigs);

    private static final SwerveModuleConstantsFactory ConstantCreator = new SwerveModuleConstantsFactory()
            .withDriveMotorGearRatio(kDriveGearRatio)
            .withSteerMotorGearRatio(kSteerGearRatio)
            .withWheelRadius(kWheelRadiusInches)
            .withSlipCurrent(kSlipCurrentA)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(steerClosedLoopOutput)
            .withDriveMotorClosedLoopOutput(driveClosedLoopOutput)
            .withSpeedAt12VoltsMps(kSpeedAt12VoltsMps)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage)
            .withFeedbackSource(SteerFeedbackType.FusedCANcoder)
            .withCouplingGearRatio(kCoupleRatio)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withCANcoderInitialConfigs(cancoderInitialConfigs);


    // Front Left
    private static final double kFrontLeftEncoderOffset = 0.052734375;
    private static final boolean kFrontLeftSteerInvert = true;

    // Front Right
    private static final double kFrontRightEncoderOffset = 0.1318359375;
    private static final boolean kFrontRightSteerInvert = true;

    // Back Left
    private static final double kBackLeftEncoderOffset = 0.33154296875;
    private static final boolean kBackLeftSteerInvert = true;

    // Back Right
    private static final double kBackRightEncoderOffset = 0.192138671875;
    private static final boolean kBackRightSteerInvert = true;

    private static final double kBackRightXPosInches = -9.625;
    private static final double kBackRightYPosInches = -13.5;


    public static final SwerveModuleConstants FrontLeft = ConstantCreator.createModuleConstants(
        Ports.Swerve.FrontLeft.TURN, 
        Ports.Swerve.FrontLeft.DRIVE, 
        Ports.Swerve.FrontLeft.ENCODER, 
        Settings.Swerve.FrontLeft.ABSOLUTE_OFFSET.getRotations(), 
        Settings.Swerve.FrontLeft.MODULE_OFFSET.getX(), 
        Settings.Swerve.FrontLeft.MODULE_OFFSET.getY(), 
        Settings.Swerve.Drive.INVERTED)
        .withSteerMotorInverted(Settings.Swerve.Turn.INVERTED);
    public static final SwerveModuleConstants FrontRight = ConstantCreator.createModuleConstants(
        Ports.Swerve.FrontRight.TURN, 
        Ports.Swerve.FrontRight.DRIVE, 
        Ports.Swerve.FrontRight.ENCODER, 
        Settings.Swerve.FrontRight.ABSOLUTE_OFFSET.getRotations(), 
        Settings.Swerve.FrontRight.MODULE_OFFSET.getX(), 
        Settings.Swerve.FrontRight.MODULE_OFFSET.getY(), 
        Settings.Swerve.Drive.INVERTED)
        .withSteerMotorInverted(Settings.Swerve.Turn.INVERTED);
    public static final SwerveModuleConstants BackLeft = ConstantCreator.createModuleConstants(
        Ports.Swerve.BackLeft.TURN, 
        Ports.Swerve.BackLeft.DRIVE, 
        Ports.Swerve.BackLeft.ENCODER, 
        Settings.Swerve.BackLeft.ABSOLUTE_OFFSET.getRotations(), 
        Settings.Swerve.BackLeft.MODULE_OFFSET.getX(), 
        Settings.Swerve.BackLeft.MODULE_OFFSET.getY(), 
        Settings.Swerve.Drive.INVERTED)
        .withSteerMotorInverted(Settings.Swerve.Turn.INVERTED);
    public static final SwerveModuleConstants BackRight = ConstantCreator.createModuleConstants(
        Ports.Swerve.BackRight.TURN, 
        Ports.Swerve.BackRight.DRIVE, 
        Ports.Swerve.BackRight.ENCODER, 
        Settings.Swerve.BackRight.ABSOLUTE_OFFSET.getRotations(), 
        Settings.Swerve.BackRight.MODULE_OFFSET.getX(), 
        Settings.Swerve.BackRight.MODULE_OFFSET.getY(), 
        Settings.Swerve.Drive.INVERTED)
        .withSteerMotorInverted(Settings.Swerve.Turn.INVERTED);
}